Repository ES2-UFPI/Altair, pull requests merged in 2022-09, with the labels that each got.

#58 Criacao classe regra#41
  altair/settings.py
  logic/Regra.py
  logic/RegraProxy.py
  logic/__init__.py
  logic/regraInterface.py
  verificador_fraude/__init__.py
  verificador_fraude/admin.py
  verificador_fraude/apps.py
  verificador_fraude/models.py
  verificador_fraude/tests/__init__.py
  verificador_fraude/tests/test_regra.py
  verificador_fraude/views.py
Labels: back-end

#59 #42 criação de toJson e loadJson e collections
  logic/Regra.py
  logic/RegraProxy.py
  utils.py
  verificador_fraude/tests/test_regra.py
Labels: back-end

#63 Persistir binario do pdf #48
  .github/workflows/dev.yml
  .github/workflows/dev_pullrequest.yml
  .github/workflows/main.yml
  .github/workflows/master.yml
  altair/settings.py
  construtor_licitacoes/static/construtor_licitacoes/js/downloadPdf.js
  construtor_licitacoes/static/construtor_licitacoes/js/getsTinyMCE.js
  construtor_licitacoes/static/construtor_licitacoes/js/save.js
  construtor_licitacoes/tests.py
  construtor_licitacoes/tests/__init__.py
  construtor_licitacoes/urls.py
  construtor_licitacoes/views.py
  requirements.txt
Labels: back-end

#65 Resolvido bug de erro com caracteres especiais #64
  construtor_licitacoes/static/construtor_licitacoes/js/save.js
Labels: bug, back-end

#66 Criação dos mecanismos de extração de texto#45
  .github/workflows/dev.yml
  .github/workflows/dev_pullrequest.yml
  .github/workflows/master.yml
  logic/Header.py
  logic/Licitacao.py
  logic/LicitacaoInterface.py
  logic/LicitacaoProxy.py
  logic/Secao.py
  staticfiles/construtor_licitacoes/css/estilo_adicionar.css
  staticfiles/construtor_licitacoes/js/downloadPdf.js
  staticfiles/construtor_licitacoes/js/getsTinyMCE.js
  staticfiles/construtor_licitacoes/js/save.js
  verificador_fraude/tests/test_extracao.py
Labels: back-end

#71 Atualizacao status bloqueio edicao #49
  construtor_licitacoes/static/construtor_licitacoes/css/estilo_adicionar.css
  construtor_licitacoes/static/construtor_licitacoes/css/estilo_construtor.css
  construtor_licitacoes/static/construtor_licitacoes/js/index.js
  construtor_licitacoes/static/construtor_licitacoes/js/save.js
  home_page/templates/home_page/base.html
  home_page/templates/home_page/index.html
  home_page/urls.py
  home_page/views.py
Labels: front-end, back-end

#73 back bloqueado na edição mensageria inserida #72
  altair/settings.py
  construtor_licitacoes/views.py
  home_page/templates/home_page/index.html
  home_page/templates/home_page/messages.html
Labels: bug, back-end

#76 Classe fraude #68
  logic/Fraude.py
Labels: back-end

#79 correção feita #78
  construtor_licitacoes/static/construtor_licitacoes/js/save.js
  construtor_licitacoes/views.py
  verificador_fraude/views.py
Labels: bug, back-end

#82 Arquivos classe achado
  logic/achado.py
  utils.py
Labels: back-end

#85 Correção bugs
  construtor_licitacoes/static/construtor_licitacoes/css/estilo_adicionar.css
  construtor_licitacoes/static/construtor_licitacoes/js/getFormsFields.js
  construtor_licitacoes/templates/construtor_licitacoes/enviarConstrucao.html
  construtor_licitacoes/templates/construtor_licitacoes/enviarGeral.html
  construtor_licitacoes/views.py
  home_page/templates/home_page/base.html
  home_page/templates/home_page/enviar.html
  home_page/templates/home_page/index.html
  verificador_fraude/static/verificador_fraude/css/estilo_verificador.css
  verificador_fraude/templates/verificador_fraude/avaliar.html
  verificador_fraude/templates/verificador_fraude/base2.html
  verificador_fraude/templates/verificador_fraude/homeAud.html
  verificador_fraude/urls.py
  verificador_fraude/views.py
Labels: bug, back-end

#86 Gestao achados#84
  logic/API.py
  logic/Achado.py
  logic/Fraude.py
  logic/Header.py
  logic/Licitacao.py
  logic/LicitacaoProxy.py
  logic/Regra.py
  logic/RegraProxy.py
  logic/Secao.py
  logic/Tokeniza.py
  logic/descricao_expressoes.py
  logic/expressoes.py
  verificador_fraude/templates/verificador_fraude/avaliar.html
  verificador_fraude/tests/auxiliar_verificacao.csv
  verificador_fraude/tests/test_liciitacao.py
  verificador_fraude/tests/test_regra.py
  verificador_fraude/urls.py
  verificador_fraude/views.py
Labels: back-end

#88 Correção do bug download em /aud #80
  verificador_fraude/views.py
Labels: bug, back-end

#104 conserto de algumas rotas de login de logout #103
  home_all/templates/home_all/homeCadastro.html
  home_all/templates/home_all/homeLogin.html
  home_all/urls.py
  home_all/views.py
  home_page/urls.py
  home_page/views.py
  utils.py
Labels: bug, back-end
