Repository ES2-UFPI/Altair, pull requests merged in 2022-10, with the labels that each got.

#105 Conserto bug rotas #103
  construtor_licitacoes/static/construtor_licitacoes/js/downloadPdf.js
  construtor_licitacoes/static/construtor_licitacoes/js/getsTinyMCE.js
  construtor_licitacoes/urls.py
  construtor_licitacoes/views.py
  home_all/views.py
Labels: bug, back-end

#100 Feedback para o licitante #94
  construtor_licitacoes/static/construtor_licitacoes/js/index.js
  home_page/templates/home_page/index.html
Labels: back-end

#107 Tela avaliação #93
  construtor_licitacoes/views.py
  home_all/views.py
  requirements.txt
  utils.py
  verificador_fraude/static/verificador_fraude/css/estilo_verificador.css
  verificador_fraude/templates/verificador_fraude/avaliar.html
  verificador_fraude/templates/verificador_fraude/base2.html
  verificador_fraude/urls.py
  verificador_fraude/views.py
Labels: back-end

#120 Test url
  home_page/urls.py
  temp_pdf/.gitkeep
  temp_txt/.gitkeep
  verificador_fraude/tests/test_arquivosAchados.py
  verificador_fraude/tests/test_url.py
Labels: bug, back-end, tests

#121 Bug edição de informações #118
  .gitignore
  construtor_licitacoes/static/construtor_licitacoes/css/estilo_adicionar.css
  construtor_licitacoes/templates/construtor_licitacoes/adicionar.html
  construtor_licitacoes/templates/construtor_licitacoes/enviarConstrucao.html
  construtor_licitacoes/templates/construtor_licitacoes/modelos.html
  construtor_licitacoes/views.py
  data/avaliacaoBD.py
  data/database.py
  data/licitacaoBD.py
  data/templatesBD.py
  data/usuarioBD.py
  home_all/static/home_all/css/estiloHome.css
  home_all/templates/home_all/home.html
  home_all/templates/home_all/homeCadastro.html
  home_all/templates/home_all/homeLogin.html
  home_all/templates/home_all/homePerfilAuditor.html
  home_all/templates/home_all/homePerfilGestor.html
  home_all/views.py
  home_page/static/home_page/assets/favicon.ico
  home_page/static/home_page/assets/lic_img_add.png
  home_page/static/home_page/assets/lic_img_demo.png
  home_page/static/home_page/assets/template_secao_exemplo.png
  home_page/templates/home_page/alterarSenha.html
  home_page/templates/home_page/base.html
  home_page/templates/home_page/enviar.html
  home_page/templates/home_page/index.html
  home_page/templates/home_page/perfil.html
  home_page/urls.py
  home_page/views.py
  logic/Tokeniza.py
  verificador_fraude/static/verificador_fraude/css/estilo_verificador.css
  verificador_fraude/templates/verificador_fraude/alterarSenha.html
  verificador_fraude/templates/verificador_fraude/base2.html
  verificador_fraude/templates/verificador_fraude/homeAud.html
  verificador_fraude/templates/verificador_fraude/perfil.html
  verificador_fraude/tests/test_url.py
  verificador_fraude/urls.py
  verificador_fraude/views.py
Labels: bug, back-end, refactoring

#125 #118 correção de bug no campo userID
  verificador_fraude/views.py
  view/templates/verificador_fraude/perfil.html
Labels: bug, back-end
